### ISSUE TITLE
get started link not working

### ISSUE THREAD

**Issue by maciejmoscicki17** [Rikarin/xui#115]
the getting started link in '/docs' seems to be outdated. I routes to '/gettings-started', while it should to '/docs/getting-started'. This results in being taken to the default page, which is a blank white screen for me. It is accompanied with an 'Uncaught in promise' error, probably thrown by the router and lack of default route handling (?).
![obraz](https://github.com/Rikarin/xui/assets/73691737/0e98734d-e473-4938-9862-c97bcd71d001)

**Comment by Rikarin** [comment]
fixed. Thanks for reporting the issue!
